### ISSUE TITLE
🐛 Duplicate condition.ValidationRule names are currently possible

### ISSUE THREAD

**Issue by ahmad-ibra** [validator-labs/validator-plugin-vsphere#376]
### Description

Currently we can have duplicate condition.ValidationRule names. For instance, a privilege rule on cluster3 would have the name `validation-cluster-cluster3`. This name is a duplicate of a compute resource rule scoped to a cluster and on the entity cluster3.

Ensure that no rules have duplicate names as this can lead to validation results getting mixed together.

### Reproduction steps

Configure the vsphere plugin as follows in validatorctl and attempt to run `validator rules check -f validator.yaml`

```
vspherePlugin:
  enabled: true
  helmRelease: null
  validator:
    auth:
      account:
        insecure: true
        password: <redacted>
        username: <redacted>
        host: <redacted>
    datacenter: Datacenter
    privilegeValidationRules:
    - name: 'Cluster: Cluster3'
      entityType: Cluster
      entityName: Cluster3
      privileges:
      - Cns.Searchable
    computeResourceRules:
    - name: 'Compute resources for Cluster: Cluster3'
      clusterName: Cluster3
      scope: Cluster
      entityName: Cluster3
      nodepoolResourceRequirements:
      - name: mgmtpool
        numberOfNodes: 3
        cpu: 1Hz
        memory: 16384Mi
        diskSpace: 60Gi
```
